### ISSUE TITLE
Failed to create meta-data for DRBD volume

### ISSUE THREAD

**Issue by i-dea2** [LINBIT/linstor-client#19] opened 2019-06-22 08:12 UTC
I've tried the following

linstor node create pm1
linstor node create pm2
linstor node create pm3
linstor storage-pool-definition create drbdpool
linstor storage-pool create lvmthin pm1 drbdpool drbdpool/drbdpool
linstor storage-pool create lvmthin pm2 drbdpool drbdpool/drbdpool
linstor storage-pool create lvmthin pm3 drbdpool drbdpool/drbdpool
linstor resource-definition create first
linstor volume-definition create first 1G --storage-pool drbdpool
linstor resource create pm3 first

No matter what I do or what guide I follow I always get
(Node: 'pm3') Failed to create meta-data for DRBD volume first/0

Proxmox also shows the drbd storage as Active: NO

**Comment by ghernadi** [comment] 2019-06-24 05:38
Hi,

If anything goes wrong in Linstor, you should see an `ErrorReport` for that incident. You can list all your error reports with `linstor error-reports list`. The list will also include all error reports from the current controller an all online satellites. You can check a specific error report with `linstor error-reports show <ErrorReport-Id>` where the `ErrorReport-Id` is something like `5D10607F-654E4-000000`.

You are looking for an error report that states that a `drbdadm ... create-dm` command failed. The error report should also contain the standard out and standard error of that external call, which should give you a hint why Linstor failed to create the metadata. If that error message does not help you, please post that error report here.

**Comment by i-dea2** [comment] 2019-06-25 12:16
============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            0.9.11
Build ID:                           275be3a971d1eb6bb4524e1274860967fca126c9
Build time:                         2019-06-11T11:21:21+00:00
Error time:                         2019-06-22 12:25:44
Node:                               srv2

============================================================

Reported error:
===============

Description:
    Failed to create meta-data for DRBD volume first/0

Category:                           LinStorException
Class name:                         VolumeException
Class canonical name:               com.linbit.linstor.storage.layer.exceptions.VolumeException
Generated at:                       Method 'createMetaData', Source file 'DrbdLayer.java', Line #735

Error message:                      Failed to create meta-data for DRBD volume first/0

Error context:
    An error occurred while processing resource 'Node: 'pm2', Rsc: 'first''

Call backtrace:

    Method                                   Native Class:Line number
    createMetaData                           N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:735
    adjustDrbd                               N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:403
    process                                  N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:248
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:655
    processResourcesAndTheirSnapshots        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:280
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:133
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:251
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:873
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:600
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:517
    run                                      N      java.lang.Thread:748

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 1.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm -vvv --max-peers 7 -- --force create-md first/0

    The external command sent the following output data:


    The external command sent the following error information:
    'first/0' not defined in your config (for this host).


Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #494

Error message:                      The external command 'drbdadm' exited with error code 1


Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.linstor.storage.layer.adapter.drbd.utils.DrbdAdm:494
    simpleAdmCommand                         N      com.linbit.linstor.storage.layer.adapter.drbd.utils.DrbdAdm:439
    createMd                                 N      com.linbit.linstor.storage.layer.adapter.drbd.utils.DrbdAdm:221
    createMetaData                           N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:684
    adjustDrbd                               N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:403
    process                                  N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:248
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:655
    processResourcesAndTheirSnapshots        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:280
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:133
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:251
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:873
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:600
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:517
    run                                      N      java.lang.Thread:748

**Comment by i-dea2** [comment] 2019-06-25 12:17
I've also found the following two errors. One under satellite the other under controller

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            0.9.11
Build ID:                           275be3a971d1eb6bb4524e1274860967fca126c9
Build time:                         2019-06-11T11:21:21+00:00
Error time:                         2019-06-22 12:34:44
Node:                               srv2

============================================================

Reported error:
===============

Category:                           Error
Class name:                         ImplementationError
Class canonical name:               com.linbit.ImplementationError
Generated at:                       Method 'devMgrLoop', Source file 'DeviceManagerImpl.java', Line #638

Error message:                      The DeviceManager service caught an unhandled exception of type AccessToDeletedDataException.


Call backtrace:

    Method                                   Native Class:Line number
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:638
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:517
    run                                      N      java.lang.Thread:748

Caused by:
==========

Category:                           RuntimeException
Class name:                         AccessToDeletedDataException
Class canonical name:               com.linbit.linstor.AccessToDeletedDataException
Generated at:                       Method 'checkDeleted', Source file 'ResourceData.java', Line #378

Error message:                      Access to deleted resource

Call backtrace:

    Method                                   Native Class:Line number
    checkDeleted                             N      com.linbit.linstor.ResourceData:378
    getAssignedNode                          N      com.linbit.linstor.ResourceData:280
    deletedObjectsCleanup                    N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:1043
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:889
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:600
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:517
    run                                      N      java.lang.Thread:748




============================================================

Application:                        LINBIT® LINSTOR
Module:                             Controller
Version:                            0.9.11
Build ID:                           275be3a971d1eb6bb4524e1274860967fca126c9
Build time:                         2019-06-11T11:21:21+00:00
Error time:                         2019-06-22 09:43:42
Node:                               srv2

============================================================

Reported error:
===============

Category:                           Error
Class name:                         ImplementationError
Class canonical name:               com.linbit.ImplementationError
Generated at:                       Method 'run', Source file 'TaskScheduleService.java', Line #243

Error message:                      Unhandled exception caught in com.linbit.linstor.tasks.TaskScheduleService

Error context:
    This exception was generated in the service thread of the service 'TaskScheduleService'

Call backtrace:

    Method                                   Native Class:Line number
    run                                      N      com.linbit.linstor.tasks.TaskScheduleService:243
    run                                      N      java.lang.Thread:748

Caused by:
==========

Category:                           RuntimeException
Class name:                         AccessToDeletedDataException
Class canonical name:               com.linbit.linstor.AccessToDeletedDataException
Generated at:                       Method 'checkDeleted', Source file 'ResourceData.java', Line #378

Error message:                      Access to deleted resource

Call backtrace:

    Method                                   Native Class:Line number
    checkDeleted                             N      com.linbit.linstor.ResourceData:378
    getAssignedNode                          N      com.linbit.linstor.ResourceData:280
    lambda$groupingBy$45                     N      java.util.stream.Collectors:907
    accept                                   N      java.util.stream.ReduceOps$3ReducingSink:169
    forEachRemaining                         N      java.util.ArrayList$ArrayListSpliterator:1382
    copyInto                                 N      java.util.stream.AbstractPipeline:482
    wrapAndCopyInto                          N      java.util.stream.AbstractPipeline:472
    evaluateSequential                       N      java.util.stream.ReduceOps$ReduceOp:708
    evaluate                                 N      java.util.stream.AbstractPipeline:234
    collect                                  N      java.util.stream.ReferencePipeline:499
    groupByNode                              N      com.linbit.linstor.tasks.RetryResourcesTask:133
    run                                      N      com.linbit.linstor.tasks.RetryResourcesTask:90
    execute                                  N      com.linbit.linstor.tasks.TaskScheduleService:262
    run                                      N      com.linbit.linstor.tasks.TaskScheduleService:211
    run                                      N      java.lang.Thread:748

**Comment by ghernadi** [comment] 2019-06-25 12:23
Did you try to install Linstor manually without using the installation scripts? If so, I would guess that you simply forgot to create `/etc/drbd.d/linstor-resources.res` with the content `include "/var/lib/linstor.d/*.res";` on your satellite

Also make sure that `/var/lib/linstor.d/` contains a `first.res` file, the same name as the resource you created in linstor.

The other two reports are interesting (possibly related to the first error). Can you reproduce them?

**Comment by i-dea2** [comment] 2019-06-25 12:42
No I have not. I've just installed the precompiled package.
/etc/drbd.d/linstor-resources.res is there and the contents are what there's supposed to: include "/var/lib/linstor.d/*.res";
first.res was created just fine under /var/lib/linstor.d/ as well as the LVM volume with the name first under the appropriate node. The problem seems to be drbd which keeps saying that it isn't not set up and there aren't any resources for it to handle.
When  I delete (via linstor) first, then both the first.res as well as the LVM volume get deleted properly.

**Comment by ghernadi** [comment] 2019-06-25 12:45
Can you please also verify that your `/etc/drbd.conf` has the needed `include "drbd.d/*.res;"` entry?

**Comment by i-dea2** [comment] 2019-06-25 15:07
# cat /etc/drbd.conf
# You can find an example in  /usr/share/doc/drbd.../drbd.conf.example

include "drbd.d/global_common.conf";
include "drbd.d/*.res";

**Comment by ghernadi** [comment] 2019-06-26 05:27
Can you post `/var/lib/linstor.d/first.res` here, just so we can verify the .res file was correctly genrearted?

Also, please try to manually execute `drbdadm dump first` (this should only try to find the .res file, parse it and print the just parsed and interpreted content, but should not do anything on DRBD level). If that fails, try to copy that `first.res` into `/etc/drbd.d/` and retry... My guess is that for some reason drbdadm does not try to look in `/var/lib/linstor.d/` - this is just to verify that guess.

**Comment by i-dea2** [comment] 2019-06-26 06:33
Unfortunately this was a production cluster and I had to remove the LVM volume and configuration as the resources where actually needed, but I can try to recreate the environment on VMs. Now that you mention this it could be that drbd did not try to look in /var/lib/linstor.d/ at all. As even drbdadm status produced "No currently configured DRBD found."

**Comment by ghernadi** [comment] 2019-06-26 06:36
Even if drbdadm would be looking for resources in all the expected folders, this message is displayed when no DRBD resource is up (only because the .res file exists does not mean that the resource is up and running). In other words, in every correctly configured DRBD setup, after executing `drbdadm down all` that message will be displayed when asking for the current status.

**Comment by raltnoeder** [comment] 2019-06-26 10:00
Also, check whether the name of the node as it is registered in LINSTOR matches the nodename of that node (the output of `uname -n` on that node), because this is required for DRBD to find that node's `on nodename` section in the resource configuration file.

**Comment by i-dea2** [comment] 2019-06-26 10:11
ouch.. that certainly didn't match and there wasn't any mention on any of the guides I've followed. Thanks

**Comment by ghernadi** [comment] 2019-06-26 12:08
Completely forgot about this. There was a bug that linstor allowed creating DRBD-resources while the uname did not match. This should be fixed in `0.9.12` - which means that the controller should reject the creation of the resource, instead of only failing at satellite side. I agree, not much of a difference for the user, but at least the message that the DRBD-layer is not supported might lead you in the correct direction. (the satellite will not support DRBD since the uname mismatches).

**Closed by ghernadi** 2019-06-26 12:08 UTC
